/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.crtp.ec135.app;

//import io.crtp.ec135.list.LinkedList;
//import static io.crtp.ec135.utilities.StringUtils.join;

import io.crtp.ec135.app.rpc.BitcoinRPCs;
import io.crtp.ec135.app.db.MariaDB;
import io.crtp.ec135.app.btc.Addresses;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {

    private static final Logger log = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {

        log.debug("Still she haunts me, phantomwise,");
        log.debug("Alice moving under skies,");
        log.debug("Never seen by waking eyes.");

        Addresses address = new Addresses(new MariaDB(), new BitcoinRPCs());
        address.scan01();

    }

    public void testTheTest() {
        log.debug("App.testTheTest - linking the method calls");
    }

}
